name: geekcontrol
description: Aplicação para controle de seus animes/mangás favoritos.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  get_it: ^8.0.3
  dotenv: ^4.2.0
  flutter_dotenv: ^5.1.0
  intl: any
  carousel_slider: ^5.0.0
  mongo_dart: ^0.10.2
  logger: ^2.2.0
  skeletonizer: ^1.4.3
  loading_indicator: ^3.1.1
  go_router: ^15.1.1
  animated_floating_buttons: ^0.0.2
  http: ^1.4.0
  sembast: ^3.7.1
  path_provider: ^2.1.3
  url_launcher: ^6.2.6
  google_fonts: ^6.2.1
  html: ^0.15.4
  permission_handler: ^12.0.0+1
  cached_network_image: ^3.3.1
  saver_gallery: ^4.0.1
  device_info_plus: ^11.4.0
  shimmer: ^3.0.0
  translator: ^1.0.3+1
  toasty_box: ^1.0.4
  provider: ^6.1.5
  scraper: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/animes_new.png
    - assets/intoxi.png
    - assets/otakuPT_icon.png
    - assets/geekcontrol_banner.png
    - assets/geekcontrol_logo.png
    - assets/default.png
    - assets/anime_united_logo.png
    - assets/banners_assets/luffy.png
    - assets/banners_assets/hitagi.png
    - assets/banners_assets/berserker.png
    - assets/banners_assets/zenitsu.png
    - assets/banners_assets/frieren.png
